twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        admin_host: '%admin_host%'
        main_host: '%main_host%'
        landing_host: '%landing_host%'
        app_scheme: '%app_scheme%'
        locale_cookie_domain: '%locale_cookie_domain%'

when@test:
    twig:
        strict_variables: true
