services:
  php:
    container_name: easyshop-php
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - easyshop

  nginx:
    container_name: easyshop-nginx
    depends_on:
      - php
    networks:
      - easyshop

  database:
    image: mysql:8.0
    container_name: easyshop-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - easyshop

  redis:
    image: redis:7-alpine
    container_name: easyshop-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - easyshop

volumes:
  db_data:
  redis_data:


networks:
  easyshop:
    driver: bridge
